name: Alistair Lamb Photography
favicon: null
layout_spectrum: 0.6549921764526516
typography_spectrum: 0.5168887099716812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.06180304940789938
  lightness: 0.38072661659680307
  saturation: 0.9511729872319847
  rhythmicContrast: 0.8698255165945739
purpose: []
